env_type: isaaclab
total_num_envs: null
auto_reset: False
ignore_terminations: False
use_rel_reward: True
seed: 0
group_size: 1

reward_coef: 1.0
use_fixed_reset_state_ids: False
max_steps_per_rollout_epoch: 10
max_episode_steps: 256 # max episode steps for truncation

video_cfg:
  save_video: False
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: "Isaac-Assemble-Trocar-G129-Dex3-Joint"
  num_envs: null
  max_episode_steps: ${env.train.max_episode_steps}
  # Note: Using "install trocar from box" yields better results than "assemble trocar from tray"
  # because the model was trained with this specific task description during data collection and fine-tuning.
  task_description: "install trocar from box"
